### ISSUE TITLE
Missing context menu entry at explorer view

### ISSUE THREAD

**Issue by SebastianSolidwork** [CSeitel/open-in-npp#2]
Command palette and shortscuts are working, but at the explorer view an entry in the context menu is missing.
I'm having Windows 10 64bit with the latest VS-Code
![image](https://user-images.githubusercontent.com/22794134/69711829-046bc580-1102-11ea-8096-a054b70adffb.png)

**Comment by CSeitel** [comment]
Hi, I think this is the context menu of the explorer tree; only the context menu of the editor view is extended by 'OpenInNpp'; I am undecided about extending the context menu of the explorer tree
because some users may not want the explorer menu getting cluttered with entries from miscellaneous extensions

**Comment by SebastianSolidwork** [comment]
@CSeitel Your are right, this is from the explorer view. Could you make it configurable? Default active ,so people see it, and deactivatable in the settings.
I'd like to open files direclty in Npp with no detour to open files first.

It works directly from the file:
![image](https://user-images.githubusercontent.com/22794134/69717439-5ca7c500-110c-11ea-88a0-a5d37e606f92.png)

**Comment by CSeitel** [comment]
Found the solution at https://stackoverflow.com/questions/46714353/how-to-customize-context-menu-in-visual-studio-code;
new version published 👍
would possibly still need to make the context menu entry disappear in case it is a directory 👎

**Comment by SebastianSolidwork** [comment]
Thanks! Opening files from the explorer view works.
Please keep the entry and directories, i find it useful. So i can open many files at once, e.g. log files which i prefer to search through by Npp.
If it's not too much effort you can make this, context menu entry at directories, configurable too.
But please keep it or wait at least for more feedback.
